### PR TITLE
Fixing repo url

### PR DESCRIPTION
**Pull request by psteinb**
I fixed the URLs by hand for now. I am sure there is a more programmatic way within Jekyll. Please review!

### CODE REVIEW

**Comment by ChristinaLK** [comment]
{{site.url}} ?

The navbar links at the bottom of the episode pages use {{relative_root_path}} -- see `_includes/episode_navbar.shtml` and `_includes/base_path.html`

**Comment by psteinb** [comment]
I thought that #6 referred to URLs in markdowns rather than episodes. But yes, good hint.

**Comment by psteinb** [comment]
`site.url` works locally. I added that here for now.

**Review by ChristinaLK — APPROVED** [review]
LGTM

**Comment by psteinb** [comment]
thanks for having a look.

**Pull request merged**
