### PR TITLE
Revert "spelling corrections using en_GB dictionary"

### PR DESCRIPTION
**Pull request by tkphd**
Reverts hpc-carpentry/hpc-shell#3

`en_GB` is the wrong dictionary, I would like to resubmit using `en_CA`.

### CODE REVIEW

**Comment by psteinb** [comment]
Can we *first* find an agreement which dictionary to use. 
As a non-native speaker, I simply do not care too much, but I'd favor a consistent choice. `en_GB` or `en_US` would be those, I'm mostly familiar with and to which many possible contributors may be familiar with.

**Comment by aturner-epcc** [comment]
I would argue for en_GB as everything else is just a corruption! ;-)

I agree with @psteinb that we should choose either en_GB or en_US as that is what most people will be familiar with. I think most lessons are en_US, so actually vote that we go for that (though it will make me shudder every time I have to write color instead of colour, catalog instead of catalogue or program instead of programme).

**Comment by ChristinaLK** [comment]
I went ahead + merged en_gb because the lessons were originally developed in Canada (and we've had a significant international presence) so british english seemed like a reasonable choice.  

But I'm happy either way -- I do think we should pick a standard and stick to it.

**Comment by tkphd** [comment]
As a newcomer to the project, my intention was to fix typos without asserting my own dictionary bias. I mistakenly used en_GB the first time through; my bad! `ispell` is almost trivial to run from `emacs`, so whatever dictionary wins the contest, it's easy to apply.

Would it make sense to merge the *spelling corrections* using en_CA, and open a new issue to decide on a universal dictionary moving forward?

If not, my vote is for en_US, for consistency with the rest of the Carpentries.

**Comment by psteinb** [comment]
I am confused. I created an issue in the lesson template repo:
https://github.com/carpentries/lesson-example/issues/231
I hope this can illuminate us ... just saw that hpc-chapel already merged the en_CA PR. I was hoping to stay conformant with carpentries material guidelines as much as possible.

**Comment by razoumov** [comment]
hpc-chapel was originally written in en_CA, so the last PR takes it back to the original version. I have nothing against conforming to the carpentries guidelines, once this issue is decided.

**Comment by psteinb** [comment]
according to [carpentries/lesson-example#231](https://github.com/carpentries/lesson-example/issues/231#issuecomment-417516918) `en_GB` should be the dictionary to use, so I'd strongly vote to not merge `en_CA`.

**Pull request closed without merging**
